"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(",")
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split(",")


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'Myapp',
    'CustomUser',

    #3rd party
    'django_ckeditor_5',
    'easyaudit',
    'widget_tweaks',
    'django_filters',
    "crispy_forms",
    "crispy_bootstrap5",
        "django_htmx",

]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_htmx.middleware.HtmxMiddleware",

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
         'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DATABASE_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': BASE_DIR / os.getenv('DATABASE_NAME', 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Adjust based on your project structure
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Only used in production

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model
AUTH_USER_MODEL = 'CustomUser.User'



CKEDITOR_5_CONFIGS = {
    'default': {
        "blockToolbar": [
            'heading', 'bold', 'italic', 'strikethrough', 'underline', 'link', 
            'bulletedList', 'numberedList', 'blockQuote', 'codeBlock', 'imageUpload', 
            'mediaEmbed', 'horizontalLine', 'highlight', 'alignment', 'subscript', 'superscript',
        ],
        "toolbar": [
            'heading', '|', 'bold', 'italic', 'strikethrough', 'underline', 'link', 
            'bulletedList', 'numberedList', 'blockQuote', '|', 'codeBlock', 'imageUpload', 
            'mediaEmbed', 'horizontalLine', 'highlight', 'alignment', 'subscript', 'superscript', 
            'undo', 'redo'
        ],
        "image": {
            "toolbar": [
                'imageTextAlternative', 'imageStyle:full', 'imageStyle:side','link', 'insertImage', 'mediaEmbed', 'fileUpload', 
            ]
        },
        "table": {
            "contentToolbar": [
                'tableColumn', 'tableRow', 'mergeTableCells'
            ]
        },
        "language": "en"
    }
}


DJANGO_EASY_AUDIT_CHECK_IF_REQUEST_USER_EXISTS = True

# settings.py

# settings.py

# DJANGO_EASY_AUDIT_UNREGISTERED_URLS_DEFAULT = [r'^/admin/', r'^/static/', r'^/favicon.ico$',r'^/login/', r'^/logout/', r'^/register/',r'^/']
DJANGO_EASY_AUDIT_REGISTERED_URLS = [
    r'^/learn/courses/',  # Existing registered URL
    r'^/learn/content/[a-zA-Z0-9-_]+/$',  # New pattern for course detail with a slug
]


MESSAGE_TAGS = {
    messages.DEBUG: 'notify',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'error',
}


UNFOLD = {
    "SITE_TITLE": "My E-Learning Admin",
    "SITE_HEADER": "E-Learning Admin",
    "SITE_URL": "/",  # Redirect when clicking on the site name
    "SHOW_ACTIONS_ON_TOP": True,  # Show action buttons on top of list
    "SHOW_ACTIONS_ON_BOTTOM": True,  # Show action buttons at bottom of list
    "TABLES_SCROLLABLE": True,  # Allow horizontal scrolling for tables
    "TABLES_NO_STRIPES": False,  # Keep striped table rows
    "PRIMARY_COLOR": "#4CAF50",  # Customize primary theme color (green)
    "SECONDARY_COLOR": "#FF9800",  # Customize secondary color (orange)
    "FONT_FAMILY": "Arial, sans-serif",  # Set custom font
}
