# Generated by Django 5.1.6 on 2025-02-13 15:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=True, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
