# Generated by Django 5.1.6 on 2025-02-19 14:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
