# Generated by Django 5.1.6 on 2025-02-19 14:40

import django_ckeditor_5.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_alter_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='contenter',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
