# Generated by Django 5.1.6 on 2025-02-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_remove_course_contenter_alter_course_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoevent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Myapp.course'),
        ),
        migrations.AddField(
            model_name='videoevent',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
