# Generated by Django 5.1.6 on 2026-08-04 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_videoevent_course_videoevent_course_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('answers', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('retries', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='videoevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='videoevent',
            name='video_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoevent',
            name='watch_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoevent',
            name='event_type',
            field=models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('ended', 'Ended'), ('watch_duration', 'Watch Duration'), ('rewatch', 'Rewatch'), ('seek_forward', 'Seek Forward'), ('playback_speed', 'Playback Speed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='videoevent',
            index=models.Index(fields=['user', 'video_id', '-timestamp'], name='Myapp_video_user_id_0076b1_idx'),
        ),
        migrations.AddIndex(
            model_name='videoevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='Myapp_video_event_t_ed0867_idx'),
        ),
        migrations.AddField(
            model_name='pagetime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
