# Generated by Django 5.1.6 on 2026-01-18 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoevent',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='videoevent',
            name='video_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoevent',
            name='event_type',
            field=models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('ended', 'Ended'), ('watch_duration', 'Watch Duration'), ('rewatch', 'Rewatch'), ('seek_forward', 'Seek Forward'), ('playback_speed', 'Playback Speed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='videoevent',
            index=models.Index(fields=['user', 'video_id', '-timestamp'], name='Myapp_video_user_id_0076b1_idx'),
        ),
        migrations.AddIndex(
            model_name='videoevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='Myapp_video_event_t_ed0867_idx'),
        ),
    ]
