# Generated by Django 5.1.6 on 2026-01-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_alter_videoevent_options_videoevent_video_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoevent',
            name='session_watch_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoevent',
            name='video_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
