# Generated by Django 5.1.6 on 2026-01-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_videoevent_session_watch_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoevent',
            name='session_watch_time',
        ),
        migrations.RemoveField(
            model_name='videoevent',
            name='video_duration',
        ),
    ]
